"""guard/ — deterministic crisis-referral filter for the CBT chatbot.

Design principle: **no referral the user sees was ever generated by the model.** The only contact
information a user can see is a hand-verified block appended by code (`footer_text`), and every
referral-shaped sentence the model produced is removed before the reply reaches the user, the
session history, the transcript or the graph.

A separate top-level add-on, like `steering/` — `cbt_kg/` reaches it only through `factory.py`.
Toggle with `REFERRAL_GUARD=0` (research mode: byte-identical to pre-guard behaviour).
"""

from .safe_generator import SafeGenerator, guard_enabled
from .sanitize import GuardResult, contains_crisis, footer_text, load_config, sanitize

__all__ = ["GuardResult", "SafeGenerator", "contains_crisis", "footer_text", "guard_enabled",
           "load_config", "sanitize"]
