"""Deterministic referral sanitizer — pure regex, no I/O beyond reading resources.json.

The invariant this file exists to hold: **no crisis referral the user sees was ever generated by
the model.** Any sentence containing something referral-shaped (a number, a URL, an organisation
name, a bracket placeholder) is removed WHOLE — including correct ones like a bare "call 988" —
and the verified footer, appended by code in therapy.py, is the only channel through which contact
information reaches a user.

Why regex and not an LLM checker: in the research self-play data an LLM judge scored dialogues
containing fabricated hotline numbers ~3.75/5 on appropriateness, i.e. it caught none of them.

Why remove the whole sentence rather than the span: deleting just the digits leaves "you can call
[removed] for free support", which still tells a distressed person that a number exists and that we
swallowed it. Same reasoning as steering/steer_runtime.py::strip_invented_numbers.

Relationship to steering/: `steer_runtime` has its own CRISIS_RE / PHONE_RE used by the steering
service's guard, which covers the steered path only. The patterns here are deliberately duplicated
rather than imported — `guard/` and `steering/` are independent add-ons and `cbt_kg/` must run with
no `steering/` folder present. guard/tests/test_sanitize.py pins these patterns as a strict superset
of that file's PHONE_RE so the deployment-side net can never be looser than the service-side one.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from pathlib import Path

RESOURCES_PATH = Path(__file__).parent / "resources.json"


@dataclass
class GuardResult:
    """Outcome of sanitizing one reply.

    clean        — the text that goes to the user AND into session.history / transcript.
    removed      — the sentences that were dropped (research record; never shown).
    entities     — what matched, as {"kind": ..., "value": ..., "known": bool}.
    crisis       — explicit crisis language was present in the reply or the user's message.
    needs_footer — the caller should append the verified footer to the OUTWARD reply only.
    """
    clean: str
    removed: list[str] = field(default_factory=list)
    entities: list[dict] = field(default_factory=list)
    crisis: bool = False
    needs_footer: bool = False


# ─────────────────────────── Detection patterns ────────────────────────────

# Sentence boundary: after . ! ? followed by whitespace, or a newline. A trailing fragment with no
# terminator stays a sentence of its own — generation is capped (MAX_NEW=96 in the steering service)
# so replies frequently end mid-clause, and "you can call 1-800-2" must still be removable.
_SENT_SPLIT = re.compile(r"(?<=[.!?])\s+|\n+")

# URLs: scheme form, www form, and bare domains. Bare domains need an explicit TLD set — a generic
# `\w+\.\w+` would match ordinary prose across a sentence boundary.
_TLD = (r"com|org|net|gov|edu|int|mil|io|co|me|info|help|health|life|support|"
        r"uk|us|ca|au|nz|ie|in|sg|th|my|ph|hk|jp|kr|de|fr|es|it|nl|se|no|dk|fi")
_URL_RE = re.compile(
    rf"(?:https?://|www\.)\S+"
    rf"|\b[a-z0-9][a-z0-9\-]*(?:\.[a-z0-9\-]+)*\.(?:{_TLD})\b(?:/[^\s,;]*)?",
    re.IGNORECASE)

# Phone-shaped spans. Split by strength, because the vocabulary gate below applies to only one of
# them: a separated or spelled-out digit group can hardly be anything BUT a number to dial, while a
# bare 2-6 digit run is usually ordinary content ("slept 3 hours", "20 minutes").
_PHONE_STRONG_RE = re.compile(
    # Two or more digit groups joined by phone separators, so it covers 1-800-273-8255,
    # 800 799 7233, (800) 273-8255, +44 20 7946 0958, the spelled-out 9-8-8 / 9-1-1, and the
    # truncated 1-800-2. A trailing ALL-CAPS group catches vanity numbers (1-800-799-SAFE);
    # requiring caps there is what stops "10268 in India" from swallowing the following word.
    r"\+?\d+(?:[-.\s()]+(?:\d+|[A-Z]{2,}))+")
# Short codes / bare numbers: 988, 741741, 10268, 12345, 987, 801, 10.
_PHONE_SHORT_RE = re.compile(r"\b\d{2,6}\b")
_PHONE_RE = re.compile(f"{_PHONE_STRONG_RE.pattern}|{_PHONE_SHORT_RE.pattern}")

# Organisation names: a capitalized phrase touching a referral noun. Handles the noun appearing
# mid-phrase ("National Crisis Recovery Center") or leading it ("Crisis Text Line").
# Used when resources.json carries no `referral_nouns`, and by SafeGenerator's panic path.
_ORG_FALLBACK_NOUNS = ["Hotline", "Helpline", "Lifeline", "Crisis", "Center", "Centre",
                       "Foundation", "Samaritans"]


def _org_re(nouns: list[str]) -> re.Pattern:
    alt = "|".join(re.escape(n) for n in nouns)
    return re.compile(
        rf"\b(?:[A-Z][\w'’-]*\s+){{1,5}}(?:{alt})\b(?:\s+[A-Z][\w'’-]*){{0,5}}"
        rf"|\b(?:{alt})(?:\s+[A-Z][\w'’-]*){{1,5}}\b")

# Bracket templates the model emits when it knows a number belongs somewhere but has none:
# "[insert hotline number]", "[phone number]", "[XXX-XXX-XXXX]".
_PLACEHOLDER_RE = re.compile(r"\[[^\]\n]{0,120}\]")
_PLACEHOLDER_HINT = re.compile(r"insert|placeholder|number|hotline|helpline|x{3,}|\d", re.IGNORECASE)

# Explicit crisis language. Superset of steering/steer_runtime.py::CRISIS_RE — that one is checked
# against the user's latest message only; this one is checked against the reply as well, so a model
# that volunteers a referral unprompted still trips the footer.
_CRISIS_RE = re.compile(
    r"(kill myself|killing myself|end my life|ending my life|take my (own )?life|suicid|"
    r"self[- ]harm|hurt myself|harming myself|don'?t want to (be here|live|wake up)|"
    r"want to die|wanna die|better off (dead|without me)|no reason to (live|go on)|"
    r"don'?t see the point( of|in)? (any of this|living|it all|anything)?|"
    r"can'?t (keep )?(going|doing this) (anymore|any more)|burden to everyone|"
    r"dark thoughts|thoughts of (dying|death)|crisis line|hotline|helpline|someone I can call|"
    r"(what|which|whose) number|who (can|could|should) I call|where (can|do) I get help|"
    r"need help right now|get me help|somewhere to turn|emergency)",
    re.IGNORECASE)


# ─────────────────────────── Config loading ────────────────────────────────

_CACHE: dict[str, dict] = {}


def load_config(path: str | Path | None = None) -> dict:
    """Read resources.json (cached). This is the single source of displayed referral text."""
    p = Path(path) if path else RESOURCES_PATH
    key = str(p.resolve())
    if key not in _CACHE:
        _CACHE[key] = json.loads(p.read_text(encoding="utf-8"))
    return _CACHE[key]


def footer_text(config: dict | None = None) -> str:
    """The verified footer, or the number-free generic line while `verified` is false.

    No number is EVER returned from here unless a human set verified=true and filled in
    verified_lines.entries with a source URL and a check date.
    """
    cfg = config if config is not None else load_config()
    header = (cfg.get("footer_header") or "").strip()
    if cfg.get("verified"):
        entries = (cfg.get("verified_lines") or {}).get("entries") or []
        lines = [e["line"] for e in entries if e.get("line")]
        if lines:
            body = "\n".join(f"- {ln}" for ln in lines)
            return f"---\n{header}\n{body}" if header else f"---\n{body}"
    generic = (cfg.get("generic_line") or "").strip()
    if not generic:
        return ""
    return f"---\n{header}\n{generic}" if header else f"---\n{generic}"


def contains_crisis(text: str) -> bool:
    return bool(_CRISIS_RE.search(text or ""))


# ─────────────────────────── Core detection ────────────────────────────────

def _norm(s: str) -> str:
    return re.sub(r"\s+", " ", (s or "")).strip().lower()


def _detect(sentence: str, cfg: dict) -> list[dict]:
    """Referral entities in ONE sentence. Empty list => the sentence is kept verbatim."""
    ents: list[dict] = []
    detection = cfg.get("detection") or {}
    known_numbers = {re.sub(r"\D", "", n) for n in detection.get("known_number_references", [])}
    known_domains = {d.lower() for d in detection.get("known_domain_references", [])}
    vocab = cfg.get("referral_vocabulary") or []
    nouns = cfg.get("referral_nouns") or _ORG_FALLBACK_NOUNS

    # Upstream referral text (e.g. the line serve_steer.py appends on crisis turns). Matched on the
    # whole sentence so it is stripped here rather than duplicating the footer or entering history.
    ns = _norm(sentence)
    if len(ns) >= 40:
        for up in cfg.get("upstream_lines") or []:
            nu = _norm(up)
            if nu and (ns in nu or nu in ns):
                ents.append({"kind": "upstream_line", "value": sentence.strip(), "known": True})
                break

    # URLs are referral entities on their own — no vocabulary gate. A fabricated path on a real
    # domain (samhsa.gov/federal-organizations/find-help-online) is the exact observed failure, so a
    # whitelisted domain is still removed; `known` only tags the log row.
    for m in _URL_RE.finditer(sentence):
        url = m.group(0).rstrip(".,;:!?)")   # sentence punctuation is not part of the URL
        host = re.sub(r"^https?://", "", url, flags=re.IGNORECASE).split("/")[0].lower()
        host = host[4:] if host.startswith("www.") else host
        ents.append({"kind": "url", "value": url, "known": host in known_domains})

    url_spans = [m.span() for m in _URL_RE.finditer(sentence)]

    def _outside_url(m: re.Match) -> bool:
        # Digits inside an already-reported URL are not a separate entity.
        return not any(a <= m.start() < b for a, b in url_spans)

    # Strong phone shapes fire unconditionally — a separated or spelled-out digit group in a
    # therapist reply is a number to dial. This is what keeps the guard a strict superset of
    # steering/steer_runtime.py::PHONE_RE, which has no vocabulary gate at all.
    for m in _PHONE_STRONG_RE.finditer(sentence):
        if _outside_url(m) and re.search(r"\d", m.group(0)):
            raw = m.group(0).strip().rstrip(".,;:!?-( )")
            ents.append({"kind": "phone", "value": raw,
                         "known": re.sub(r"\D", "", raw) in known_numbers})

    # A bare short code needs referral vocabulary in the same sentence, so ordinary CBT content
    # survives ("I only slept 3 hours", "give yourself 20 minutes of quiet time") — UNLESS it is a
    # documented crisis number, where a bare mention is a referral no matter how it is phrased.
    has_vocab = any(re.search(rf"\b{re.escape(w)}\b", sentence, re.IGNORECASE) for w in vocab)
    for m in _PHONE_SHORT_RE.finditer(sentence):
        if not _outside_url(m):
            continue
        raw = m.group(0).strip()
        digits = re.sub(r"\D", "", raw)
        is_known = digits in known_numbers
        if not (has_vocab or is_known):
            continue
        if any(a <= m.start() < b for a, b in
               [(x.start(), x.end()) for x in _PHONE_STRONG_RE.finditer(sentence)]):
            continue    # already reported by the strong pattern
        ents.append({"kind": "phone", "value": raw, "known": is_known})

    # A capitalized phrase built around a referral noun ("the National Crisis Recovery Center") is
    # never ordinary CBT content, so this needs no vocabulary gate either.
    if nouns:
        for m in _org_re(nouns).finditer(sentence):
            ents.append({"kind": "org", "value": m.group(0).strip(), "known": False})

    for m in _PLACEHOLDER_RE.finditer(sentence):
        if _PLACEHOLDER_HINT.search(m.group(0)):
            ents.append({"kind": "placeholder", "value": m.group(0), "known": False})

    return ents


def split_sentences(text: str) -> list[str]:
    """Split on . ! ? and newlines, keeping any unterminated trailing fragment."""
    return [p for p in (s.strip() for s in _SENT_SPLIT.split(text or "")) if p]


def sanitize(text: str, config: dict | None = None,
             user_message: str = "") -> GuardResult:
    """Remove every sentence carrying a referral entity; substitute the canonical sentence once.

    `user_message` is the client's latest turn, checked for crisis language alongside the reply.
    """
    cfg = config if config is not None else load_config()
    canonical = (cfg.get("canonical_sentence") or "").strip()

    kept: list[str] = []
    removed: list[str] = []
    entities: list[dict] = []
    substituted = False

    for sentence in split_sentences(text):
        ents = _detect(sentence, cfg)
        if not ents:
            kept.append(sentence)
            continue
        removed.append(sentence)
        entities.extend(ents)
        # At most ONE canonical sentence per reply, at the position of the first removal, so the
        # model's next-turn context keeps a coherent referent for "okay, I'll call them".
        if not substituted and canonical:
            kept.append(canonical)
            substituted = True

    clean = re.sub(r"\s{2,}", " ", " ".join(kept)).strip()
    if removed and not clean and canonical:
        clean = canonical

    crisis = contains_crisis(text) or contains_crisis(user_message)
    return GuardResult(clean=clean, removed=removed, entities=entities, crisis=crisis,
                       needs_footer=bool(crisis or removed))
